// Blog Generation Pipeline - Audio Jones Voice & AEO Optimization
// Transforms Perplexity research into Audio Jones branded content

import { perplexityClient, ResearchResult } from './perplexity';
import { BlogDraft, PillarType, CTAType, PILLARS, calculateReadingTime, generateSlug, validateBrandVoice } from '../models/blog';

export interface GenerationContext {
  pillar: PillarType;
  topic: string;
  persona: string;
  intent: string;
  targetLength?: number; // words
  ctaType?: CTAType;
  framework?: string;
}

export interface GenerationResult {
  draft: Partial<BlogDraft>;
  voiceValidation: {
    isValid: boolean;
    feedback: string[];
  };
  aeoScore: number;
  researchUsed: ResearchResult;
}

export interface LLMRequest {
  model: string;
  messages: Array<{
    role: 'system' | 'user' | 'assistant';
    content: string;
  }>;
  temperature?: number;
  max_tokens?: number;
  top_p?: number;
  frequency_penalty?: number;
  presence_penalty?: number;
}

class BlogGenerator {
  private openaiApiKey: string | null = null;
  private openaiBaseUrl: string = 'https://api.openai.com/v1';

  private initializeOpenAI() {
    if (!this.openaiApiKey) {
      this.openaiApiKey = process.env.OPENAI_API_KEY!;
      
      if (!this.openaiApiKey) {
        throw new Error('OPENAI_API_KEY environment variable is required');
      }
    }
  }

  async generateBlog(context: GenerationContext): Promise<GenerationResult> {
    // Step 1: Research the topic
    const researchResult = await perplexityClient.research({
      pillar: context.pillar,
      topic: context.topic,
      persona: context.persona,
      intent: context.intent,
      currentDate: new Date().toISOString().split('T')[0]
    });

    // Step 2: Load Audio Jones voice guard and AEO partial
    const voiceGuard = this.getAudioJonesVoiceGuard();
    const aeoPartial = this.getAEOPartial(context.pillar);

    // Step 3: Generate blog content
    const blogContent = await this.generateContentWithVoice(
      researchResult,
      context,
      voiceGuard,
      aeoPartial
    );

    // Step 4: Validate Audio Jones voice
    const voiceValidation = validateBrandVoice(blogContent.content);

    // Step 5: Calculate AEO score
    const aeoScore = this.calculateAEOScore(blogContent);

    // Step 6: Create draft object
    const draft: Partial<BlogDraft> = {
      pillar: context.pillar,
      source: 'perplexity',
      status: 'needs_review',
      title: blogContent.title,
      slug: generateSlug(blogContent.title),
      content: blogContent.content,
      seoTitle: blogContent.seoTitle,
      seoDescription: blogContent.seoDescription,
      seoKeywords: blogContent.seoKeywords,
      ogImage: blogContent.ogImage,
      faqs: JSON.stringify(blogContent.faqs),
      keyTakeaways: blogContent.keyTakeaways,
      structuredData: JSON.stringify(blogContent.structuredData),
      ctaType: blogContent.ctaType,
      ctaHeadline: blogContent.ctaHeadline,
      ctaDescription: blogContent.ctaDescription,
      ctaLink: blogContent.ctaLink,
      researchPayload: JSON.stringify(researchResult),
      frameworkUsed: context.framework as any,
      readingTime: calculateReadingTime(blogContent.content)
    };

    return {
      draft,
      voiceValidation,
      aeoScore,
      researchUsed: researchResult
    };
  }

  private async generateContentWithVoice(
    research: ResearchResult,
    context: GenerationContext,
    voiceGuard: string,
    aeoPartial: any
  ): Promise<{
    title: string;
    content: string;
    seoTitle: string;
    seoDescription: string;
    seoKeywords: string[];
    ogImage?: string;
    faqs: Array<{ q: string; a: string }>;
    keyTakeaways: string[];
    structuredData: any;
    ctaType: CTAType;
    ctaHeadline: string;
    ctaDescription: string;
    ctaLink: string;
  }> {
    // Initialize OpenAI only when needed
    this.initializeOpenAI();
    
    const systemPrompt = this.buildSystemPrompt(context.pillar, voiceGuard);
    const userPrompt = this.buildUserPrompt(research, context, aeoPartial);

    const request: LLMRequest = {
      model: 'gpt-4',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt }
      ],
      temperature: 0.7,
      max_tokens: 4000,
      frequency_penalty: 0.1,
      presence_penalty: 0.1
    };

    try {
      const response = await fetch(`${this.openaiBaseUrl}/chat/completions`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${this.openaiApiKey}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(request)
      });

      if (!response.ok) {
        throw new Error(`OpenAI API error: ${response.status} ${response.statusText}`);
      }

      const data = await response.json();
      const content = data.choices[0]?.message?.content;

      if (!content) {
        throw new Error('No content generated by LLM');
      }

      return this.parseGeneratedContent(content, context);
    } catch (error) {
      console.error('Blog generation failed:', error);
      throw new Error(`Generation failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  private buildSystemPrompt(pillar: PillarType, voiceGuard: string): string {
    const pillarConfig = PILLARS[pillar];
    
    return `${voiceGuard}

You are a specialized content creator for Audio Jones / AJ DIGITAL LLC, focusing on the ${pillarConfig.label} pillar.

CONTENT REQUIREMENTS:
- Write in Audio Jones' operator voice: practical, results-focused, Miami-forward
- Target length: 1500-2500 words
- Include framework references (EPM, ASI, PR, AOF) where relevant
- Maintain Miami operator perspective
- Focus on predictable growth and automation
- Avoid generic marketing language and buzzwords

CONTENT STRUCTURE:
1. Hook (attention-grabbing opener)
2. Problem/Opportunity identification
3. Solution/Framework explanation
4. Tactical implementation
5. Results/Case studies
6. Action steps
7. CTA

SEO/AEO OPTIMIZATION:
- Include H2 and H3 headings
- Use bullet points and numbered lists
- Incorporate target keywords naturally
- Create FAQ section
- Include key takeaways box
- Add structured data elements

OUTPUT FORMAT:
Provide your response as a JSON object with these fields:
{
  "title": "Compelling title (60-70 characters)",
  "seoTitle": "SEO-optimized title (55-60 characters)",
  "seoDescription": "Meta description (150-160 characters)",
  "seoKeywords": ["keyword1", "keyword2", "keyword3"],
  "content": "Full markdown content",
  "faqs": [{"q": "Question?", "a": "Answer"}],
  "keyTakeaways": ["takeaway1", "takeaway2"],
  "structuredData": {"@type": "Article", ...},
  "ctaType": "newsletter|podcast|services|lead_magnet",
  "ctaHeadline": "CTA headline",
  "ctaDescription": "CTA description",
  "ctaLink": "CTA link"
}`;
  }

  private buildUserPrompt(research: ResearchResult, context: GenerationContext, aeoPartial: any): string {
    return `Create a comprehensive blog post using this research data:

RESEARCH SUMMARY:
${research.summary}

KEY POINTS:
${research.keyPoints.map(point => `• ${point}`).join('\n')}

TRENDING DEVELOPMENTS:
${research.trends.map(trend => `• ${trend}`).join('\n')}

STRATEGIC INSIGHTS:
${research.insights.map(insight => `• ${insight}`).join('\n')}

ACTIONABLE ADVICE:
${research.actionableAdvice.map(advice => `• ${advice}`).join('\n')}

QUOTABLE STATISTICS:
${research.quotableStats.map(stat => `• ${stat}`).join('\n')}

SOCIAL PROOF:
${research.socialProof.map(proof => `• ${proof}`).join('\n')}

CONTENT CONTEXT:
- Pillar: ${research.pillar}
- Topic: ${research.topic}
- Target Persona: ${context.persona}
- Content Intent: ${context.intent}
- Framework Focus: ${context.framework || 'General Audio Jones approach'}

AEO OPTIMIZATION GUIDE:
${JSON.stringify(aeoPartial, null, 2)}

SPECIFIC REQUIREMENTS:
1. Write for ${context.persona}s seeking ${context.intent}-focused content
2. Include specific, actionable implementation steps
3. Reference Audio Jones frameworks where relevant
4. Create compelling headlines and subheadlines
5. Include quotable statistics from research
6. Add FAQ section addressing common questions
7. End with strong CTA aligned with ${context.ctaType || 'newsletter'} goal

Remember: Audio Jones clients expect operator-level insights, not surface-level content. Make this authoritative and immediately actionable.`;
  }

  private parseGeneratedContent(content: string, context: GenerationContext): any {
    try {
      // Try to parse as JSON first
      const parsed = JSON.parse(content);
      
      // Validate required fields
      if (!parsed.title || !parsed.content) {
        throw new Error('Generated content missing required fields');
      }

      // Set defaults for missing optional fields
      return {
        title: parsed.title,
        content: parsed.content,
        seoTitle: parsed.seoTitle || parsed.title,
        seoDescription: parsed.seoDescription || this.generateDefaultDescription(parsed.title),
        seoKeywords: parsed.seoKeywords || this.generateDefaultKeywords(context),
        ogImage: parsed.ogImage,
        faqs: parsed.faqs || [],
        keyTakeaways: parsed.keyTakeaways || [],
        structuredData: parsed.structuredData || this.generateDefaultStructuredData(parsed),
        ctaType: parsed.ctaType || context.ctaType || 'newsletter',
        ctaHeadline: parsed.ctaHeadline || this.generateDefaultCTAHeadline(context.ctaType || 'newsletter'),
        ctaDescription: parsed.ctaDescription || this.generateDefaultCTADescription(context.ctaType || 'newsletter'),
        ctaLink: parsed.ctaLink || this.generateDefaultCTALink(context.ctaType || 'newsletter')
      };
    } catch (error) {
      // Fallback: parse as markdown with basic structure
      console.warn('Failed to parse JSON, using fallback parser:', error);
      return this.parseMarkdownContent(content, context);
    }
  }

  private parseMarkdownContent(content: string, context: GenerationContext): any {
    const lines = content.split('\n');
    const title = lines.find(line => line.startsWith('# '))?.replace('# ', '') || context.topic;
    
    return {
      title,
      content,
      seoTitle: title,
      seoDescription: this.generateDefaultDescription(title),
      seoKeywords: this.generateDefaultKeywords(context),
      faqs: [],
      keyTakeaways: this.extractKeyTakeaways(content),
      structuredData: this.generateDefaultStructuredData({ title, content }),
      ctaType: context.ctaType || 'newsletter',
      ctaHeadline: this.generateDefaultCTAHeadline(context.ctaType || 'newsletter'),
      ctaDescription: this.generateDefaultCTADescription(context.ctaType || 'newsletter'),
      ctaLink: this.generateDefaultCTALink(context.ctaType || 'newsletter')
    };
  }

  private calculateAEOScore(content: any): number {
    let score = 0;
    const maxScore = 100;

    // Title optimization (15 points)
    if (content.title && content.title.length >= 50 && content.title.length <= 70) {
      score += 15;
    } else if (content.title) {
      score += 8;
    }

    // Meta description (10 points)
    if (content.seoDescription && content.seoDescription.length >= 150 && content.seoDescription.length <= 160) {
      score += 10;
    } else if (content.seoDescription) {
      score += 5;
    }

    // Keywords (10 points)
    if (content.seoKeywords && content.seoKeywords.length >= 3) {
      score += 10;
    }

    // Content structure (20 points)
    const hasHeadings = /#{2,3}\s/.test(content.content);
    const hasList = /^[\*\-\+]\s/m.test(content.content);
    const hasNumbers = /^\d+\.\s/m.test(content.content);
    
    if (hasHeadings) score += 8;
    if (hasList) score += 6;
    if (hasNumbers) score += 6;

    // FAQs (15 points)
    if (content.faqs && content.faqs.length >= 3) {
      score += 15;
    } else if (content.faqs && content.faqs.length > 0) {
      score += 8;
    }

    // Key takeaways (10 points)
    if (content.keyTakeaways && content.keyTakeaways.length >= 3) {
      score += 10;
    }

    // Structured data (10 points)
    if (content.structuredData && typeof content.structuredData === 'object') {
      score += 10;
    }

    // Content length (10 points)
    const wordCount = content.content.split(/\s+/).length;
    if (wordCount >= 1500 && wordCount <= 2500) {
      score += 10;
    } else if (wordCount >= 1000) {
      score += 5;
    }

    return Math.min(score, maxScore);
  }

  private getAudioJonesVoiceGuard(): string {
    return `AUDIO JONES VOICE GUARD - CRITICAL COMPLIANCE

You are writing for Audio Jones / AJ DIGITAL LLC, the Miami-based AI branding and marketing agency.

REQUIRED VOICE CHARACTERISTICS:
✅ Operator perspective (practical, results-focused)
✅ Miami-forward attitude (confident, ambitious)
✅ Framework-driven approach (EPM, ASI, PR, AOF)
✅ Predictable growth focus
✅ Automation emphasis
✅ Data-driven insights

FORBIDDEN LANGUAGE:
❌ "We believe" or "We think"
❌ "Cutting-edge" or "Revolutionary"
❌ "Game-changing" or generic superlatives
❌ Theoretical concepts without practical application
❌ Generic marketing speak

REQUIRED ELEMENTS:
- Must mention "Audio Jones" or "AJ DIGITAL" at least once
- Include framework references where relevant
- Maintain Miami operator confidence
- Focus on predictable, systematic approaches
- Provide actionable, implementable advice

TONE: Confident operator sharing proven systems, not consultant selling services.`;
  }

  private getAEOPartial(pillar: PillarType): any {
    const aeoPartials = {
      ai: {
        targetKeywords: ['AI marketing', 'marketing automation', 'AI tools for creators', 'predictive marketing'],
        commonQuestions: [
          'How can AI improve marketing ROI?',
          'What AI tools should marketers use?',
          'How to implement AI in marketing strategy?',
          'What are the best AI marketing automation tools?'
        ],
        structuredDataType: 'HowTo',
        relatedTopics: ['machine learning', 'automation', 'data analytics', 'personalization']
      },
      marketing: {
        targetKeywords: ['SEO optimization', 'marketing funnels', 'conversion optimization', 'marketing automation'],
        commonQuestions: [
          'How to build high-converting marketing funnels?',
          'What are the best SEO practices?',
          'How to improve conversion rates?',
          'What marketing automation tools work best?'
        ],
        structuredDataType: 'HowTo',
        relatedTopics: ['lead generation', 'email marketing', 'content marketing', 'analytics']
      },
      'podcast-news': {
        targetKeywords: ['podcast marketing', 'creator economy', 'content monetization', 'audience growth'],
        commonQuestions: [
          'How to grow podcast audience?',
          'What are the latest creator economy trends?',
          'How to monetize podcast content?',
          'Best practices for podcast marketing?'
        ],
        structuredDataType: 'NewsArticle',
        relatedTopics: ['content creation', 'audience building', 'monetization', 'social media']
      },
      'tech-business-trends': {
        targetKeywords: ['business technology', 'startup trends', 'tech innovation', 'business growth'],
        commonQuestions: [
          'What are the latest business technology trends?',
          'How can startups leverage new technologies?',
          'What technologies drive business growth?',
          'How to stay ahead of tech trends?'
        ],
        structuredDataType: 'Article',
        relatedTopics: ['innovation', 'digital transformation', 'scaling', 'competitive advantage']
      },
      'personal-brand': {
        targetKeywords: ['personal branding', 'thought leadership', 'brand building', 'professional reputation'],
        commonQuestions: [
          'How to build a strong personal brand?',
          'What makes an effective thought leader?',
          'How to establish professional authority?',
          'Best strategies for personal brand growth?'
        ],
        structuredDataType: 'HowTo',
        relatedTopics: ['networking', 'content strategy', 'social media', 'reputation management']
      }
    };

    return aeoPartials[pillar] || aeoPartials.ai;
  }

  private generateDefaultDescription(title: string): string {
    return `${title.substring(0, 140)}... - Audio Jones insights for predictable growth.`;
  }

  private generateDefaultKeywords(context: GenerationContext): string[] {
    const baseKeywords = ['Audio Jones', 'marketing automation', 'predictable growth'];
    const pillarKeywords = this.getAEOPartial(context.pillar).targetKeywords;
    return [...baseKeywords, ...pillarKeywords.slice(0, 2)];
  }

  private generateDefaultStructuredData(content: any): any {
    return {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: content.title,
      author: {
        '@type': 'Organization',
        name: 'Audio Jones / AJ DIGITAL LLC'
      },
      publisher: {
        '@type': 'Organization',
        name: 'Audio Jones',
        logo: {
          '@type': 'ImageObject',
          url: 'https://audiojones.com/logo-icon.svg'
        }
      },
      datePublished: new Date().toISOString(),
      dateModified: new Date().toISOString()
    };
  }

  private generateDefaultCTAHeadline(ctaType: CTAType): string {
    const headlines = {
      newsletter: 'Get Audio Jones Weekly Growth Insights',
      podcast: 'Listen to the Audio Jones Podcast',
      services: 'Scale Your Business with Audio Jones',
      lead_magnet: 'Download Our Free Growth Framework'
    };
    return headlines[ctaType];
  }

  private generateDefaultCTADescription(ctaType: CTAType): string {
    const descriptions = {
      newsletter: 'Join 5,000+ operators getting weekly insights on predictable growth and marketing automation.',
      podcast: 'Tune in for operator insights, Miami-forward perspective, and proven growth frameworks.',
      services: 'Work with the Audio Jones team to implement systematic growth strategies for your business.',
      lead_magnet: 'Get our proven framework for predictable growth and marketing automation.'
    };
    return descriptions[ctaType];
  }

  private generateDefaultCTALink(ctaType: CTAType): string {
    const links = {
      newsletter: '/newsletter',
      podcast: '/podcast',
      services: '/services',
      lead_magnet: '/resources/growth-framework'
    };
    return links[ctaType];
  }

  private extractKeyTakeaways(content: string): string[] {
    const takeawayPatterns = [
      /^[-•*]\s*(.+)$/gm,
      /Key takeaway[s]?[:\s]*(.*)/gi,
      /Important[:\s]*(.*)/gi
    ];

    for (const pattern of takeawayPatterns) {
      const matches = [...content.matchAll(pattern)];
      if (matches.length > 0) {
        return matches.map(match => match[1].trim()).slice(0, 5);
      }
    }

    // Fallback: extract first few bullet points
    const bullets = content.match(/^[-•*]\s*(.+)$/gm);
    return bullets ? bullets.slice(0, 3).map(b => b.replace(/^[-•*]\s*/, '')) : [];
  }
}

// Lazy initialization to prevent environment variable access during module loading
let _blogGenerator: BlogGenerator | null = null;

export const blogGenerator = new Proxy({} as BlogGenerator, {
  get(target, prop) {
    if (!_blogGenerator) {
      _blogGenerator = new BlogGenerator();
    }
    const value = (_blogGenerator as any)[prop];
    return typeof value === 'function' ? value.bind(_blogGenerator) : value;
  }
});