import { MetadataRoute } from "next";
import { BLOG_TOPIC_CLUSTERS } from "@/content/blog-topics";
import { FRAMEWORKS } from "@/content/frameworks";
import { INSIGHTS } from "@/content/insights";
import { siteConfig } from "@/lib/site";

// `lastModified` is deliberately omitted on every route whose modification date
// we cannot establish honestly. It previously carried a single build-time
// `new Date()`, which stamped all 32 entries with the moment of the build and
// told crawlers every page changes on every deploy. Deriving it from
// `git log` is not an option either: no workflow sets `fetch-depth`, so CI
// checks out at depth 1 and every path would report HEAD's date — the same lie
// with extra steps. An absent `lastModified` is valid sitemap XML; a wrong one
// is a false signal. Sanity posts keep their real dates, which are trustworthy.

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const base = siteConfig.url;

  // ── Static public routes ──────────────────────────────────────────────────
  // Mirror the 7-item primary nav + the 2 right-side CTAs introduced by the
  // 2026-05-10 nav restructure, plus crawlable supporting surfaces.
  const staticRoutes: MetadataRoute.Sitemap = [
    // Primary nav
    { url: base,                                        changeFrequency: "weekly",  priority: 1    },
    { url: `${base}/solutions`,                         changeFrequency: "weekly",  priority: 0.95 },
    { url: `${base}/resources`,                         changeFrequency: "weekly",  priority: 0.7  },
    { url: `${base}/agents`,                            changeFrequency: "weekly",  priority: 0.9  },
    { url: `${base}/agents/responseos`,                 changeFrequency: "weekly",  priority: 0.9  },
    { url: `${base}/services`,                          changeFrequency: "weekly",  priority: 0.9  },
    { url: `${base}/case-studies`,                      changeFrequency: "weekly",  priority: 0.9  },
    { url: `${base}/insights`,                          changeFrequency: "weekly",  priority: 0.85 },
    { url: `${base}/roi-calculator`,                    changeFrequency: "weekly",  priority: 0.9  },
    { url: `${base}/workshops`,                         changeFrequency: "weekly",  priority: 0.85 },
    // Right-side header CTAs
    { url: `${base}/ai-readiness-diagnostic`,           changeFrequency: "monthly", priority: 0.9  },
    { url: `${base}/book-a-call`,                       changeFrequency: "monthly", priority: 0.85 },
    // Supporting surfaces
    { url: `${base}/founder-intelligence`,              changeFrequency: "weekly",  priority: 0.85 },
    { url: `${base}/founder-intelligence/diagnostic`,   changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/founder-gravity-audit`,             changeFrequency: "monthly", priority: 0.9  },
    { url: `${base}/founder-gravity-audit/diagnostic`,  changeFrequency: "monthly", priority: 0.9  },
    { url: `${base}/apply`,                             changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/pricing`,                           changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/frameworks`,                        changeFrequency: "monthly", priority: 0.8  },
    { url: `${base}/blog`,                              changeFrequency: "weekly",  priority: 0.8  },
    { url: `${base}/about`,                             changeFrequency: "monthly", priority: 0.6  },
  ];

  // ── Dynamic framework routes (from content file) ──────────────────────────
  const frameworkRoutes: MetadataRoute.Sitemap = FRAMEWORKS.map((f) => ({
    url: `${base}/frameworks/${f.slug}`,
    changeFrequency: "monthly",
    priority: 0.8,
  }));

  // ── Dynamic insight routes (from content file) ────────────────────────────
  const insightRoutes: MetadataRoute.Sitemap = INSIGHTS.map((i) => ({
    url: `${base}/insights/${i.slug}`,
    changeFrequency: "monthly",
    priority: 0.75,
  }));

  // ── Static blog topic clusters ────────────────────────────────────────────
  // These render without Sanity and are statically generated by
  // `blog/topic/[slug]`, so they are real crawlable pages. Sanity-defined
  // clusters are merged in by that route's `generateStaticParams` and are not
  // enumerable here without the dataset.
  const blogTopicRoutes: MetadataRoute.Sitemap = Object.keys(
    BLOG_TOPIC_CLUSTERS
  ).map((slug) => ({
    url: `${base}/blog/topic/${slug}`,
    changeFrequency: "monthly",
    priority: 0.7,
  }));

  // ── Dynamic Sanity blog post routes ──────────────────────────────────────
  // Only fetched when NEXT_PUBLIC_SANITY_PROJECT_ID is configured.
  // If Sanity is not connected, /blog is still in staticRoutes above — no crash.
  let blogPostRoutes: MetadataRoute.Sitemap = [];
  if (process.env.NEXT_PUBLIC_SANITY_PROJECT_ID) {
    try {
      const { safeFetch } = await import("@/lib/sanity/client");
      const { SITEMAP_POSTS_QUERY } = await import("@/lib/sanity/queries");
      const posts = await safeFetch<Array<{ slug: string; lastModified?: string }>>(
        SITEMAP_POSTS_QUERY
      );
      if (posts) {
        blogPostRoutes = posts.map((p) => ({
          url: `${base}/blog/${p.slug}`,
          // Only Sanity knows a real modification date. Omit rather than invent.
          ...(p.lastModified ? { lastModified: new Date(p.lastModified) } : {}),
          changeFrequency: "weekly",
          priority: 0.75,
        }));
      }
    } catch {
      // Sanity fetch failed — degrade gracefully, sitemap still generates
    }
  }

  return [
    ...staticRoutes,
    ...frameworkRoutes,
    ...insightRoutes,
    ...blogTopicRoutes,
    ...blogPostRoutes,
  ];
}
